# Generated by Django 4.2 on 2024-05-12 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0012_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nomor_hp',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tanggal_lahir',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
