# Generated by Django 4.2 on 2024-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0014_kabupaten_kecamatan_kelurahan_provinsi_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='berat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
