# Generated by Django 4.2 on 2024-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0015_produkitem_berat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alamatpengiriman',
            name='alamat_1',
        ),
        migrations.RemoveField(
            model_name='alamatpengiriman',
            name='alamat_2',
        ),
        migrations.RemoveField(
            model_name='alamatpengiriman',
            name='negara',
        ),
        migrations.AddField(
            model_name='address',
            name='kode_pos',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='nama_penerima',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alamatpengiriman',
            name='detail_alamat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alamatpengiriman',
            name='kabupaten',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alamatpengiriman',
            name='kecamatan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alamatpengiriman',
            name='kelurahan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alamatpengiriman',
            name='nama_penerima',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alamatpengiriman',
            name='provinsi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PR', 'Kurir Pribadi'), ('EX', 'Kurir Eksternal')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alamatpengiriman',
            name='kode_pos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'COD')], max_length=1),
        ),
    ]
