# Generated by Django 4.2 on 2024-07-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0016_remove_alamatpengiriman_alamat_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('D', 'Delivered')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'COD'), ('T', 'Transfer Manual (BCA)')], max_length=1),
        ),
    ]
