# Generated by Django 4.2 on 2024-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0016_remove_alamatpengiriman_alamat_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'COD'), ('T', 'Transfer Manual (BCA)')], max_length=1),
        ),
    ]
