# Generated by Django 4.2 on 2024-07-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0017_alter_payment_payment_option'),
        ('toko', '0017_order_status_alter_payment_payment_option'),
    ]

    operations = [
    ]
