# Generated by Django 4.2 on 2024-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0018_merge_20240728_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('EP', 'Epson'), ('CN', 'Cannon'), ('BR', 'Brother'), ('HP', 'HP')], max_length=2),
        ),
    ]
