# Generated by Django 4.2 on 2024-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0019_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('B', 'Belum di bayar'), ('S', 'Pembayaran berhasil'), ('F', 'Pembayaran gagal')], default='B', max_length=1),
        ),
    ]
