# Generated by Django 4.2 on 2024-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0020_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
