# Generated by Django 4.2 on 2024-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0021_payment_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
