# Generated by Django 4.2 on 2024-07-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0024_remove_order_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='shipping_cost',
        ),
    ]
