# Generated by Django 4.2 on 2024-08-01 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0025_remove_payment_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabupaten',
            name='id_provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupatens', to='toko.provinsi'),
        ),
        migrations.AlterField(
            model_name='kecamatan',
            name='id_kabupaten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatans', to='toko.kabupaten'),
        ),
        migrations.AlterField(
            model_name='kelurahan',
            name='id_kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelurahans', to='toko.kecamatan'),
        ),
    ]
