# Generated by Django 4.2 on 2024-08-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0026_alter_kabupaten_id_provinsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nomor_resi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Dikemas'), ('S', 'Dikirim (Kurir Internal)'), ('D', 'Pesanan Sampai')], default='P', max_length=1),
        ),
    ]
