# Generated by Django 4.2 on 2024-08-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0027_order_nomor_resi_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='nomor_handphone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Dikemas'), ('S', 'Dikirim (Kurir)'), ('D', 'Pesanan Sampai')], default='P', max_length=1),
        ),
    ]
