# Generated by Django 4.2 on 2024-08-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0028_address_nomor_handphone_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alamatpengiriman',
            name='nomor_handphone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
