# Generated by Django 4.2 on 2024-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0030_alter_payment_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_courier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
