# Generated by Django 4.2 on 2024-08-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0031_alter_order_shipping_courier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkitem',
            options={'ordering': ['nama_produk']},
        ),
    ]
